import { TestStatus } from "@prisma/client";

export interface ICreateAbTestRequest {
  name: string;
  original_product_id: number;
  // Note: variant_product_id is generated by the service via Tiendanube API, not provided by the client
  // The client provides the modifications they want to apply to the variant
  variant_modifications: {
    name?: string;
    description?: string;
    prices?: any[]; // Simplified for MVP, depends on tiendanube structure
    images?: any[];
  };
}

export interface IAbTestResponse {
  id: string;
  store_id: number;
  name: string;
  status: TestStatus;
  original_product_id: number;
  variant_product_id: number;
  original_views: number;
  variant_views: number;
  original_sales: number;
  variant_sales: number;
  created_at: Date;
  updated_at: Date;
}
