import { TestStatus } from "@prisma/client";

export interface IVariantModifications {
  name?: string;
  description?: string;
  /**
   * If provided, this price will be applied to every variant of the cloned product.
   * Uses Tiendanube's variant price field (a numeric string).
   */
  price?: string;
  /**
   * If provided, this promotional price will be applied to every variant of the cloned product.
   */
  promotional_price?: string;
  /**
   * If provided, replaces the product images entirely.
   * Each item must have a `src` field (public URL) OR an `attachment` field (base64) 
   * with a `filename`.
   */
  images?: { src?: string; attachment?: string; filename?: string }[];
  /**
   * Optional video URL for the product variant (e.g. YouTube or Vimeo link).
   */
  video_url?: string;
}

export interface ICreateAbTestRequest {
  name: string;
  original_product_id: number;
  // Note: variant_product_id is generated by the service via Tiendanube API, not provided by the client
  // The client provides the modifications they want to apply to the variant
  variant_modifications: IVariantModifications;
}

export interface IAbTestResponse {
  id: string;
  store_id: number;
  name: string;
  status: TestStatus;
  original_product_id: number;
  variant_product_id: number;
  original_views: number;
  variant_views: number;
  original_sales: number;
  variant_sales: number;
  created_at: Date;
  updated_at: Date;
}
